version: "3"

tasks:
    deploy:
        desc: Copia archivos del proyecto al directorio de Apache
        cmds:
            - sudo cp -r . /var/www/html/semana5/tallermvcphp/
            - sudo chown -R apache:apache /var/www/html/semana5/tallermvcphp/
            - sudo chmod -R 755 /var/www/html/semana5/tallermvcphp/
            - sudo semanage fcontext -a -t httpd_sys_content_t "/var/www/html/semana5/tallermvcphp(/.*)?"
            - sudo restorecon -Rv /var/www/html/semana5/tallermvcphp

    clean:
        desc: Elimina archivos del proyecto en el directorio de Apache
        cmds:
            - sudo rm -rf /var/www/html/semana5/tallermvcphp/
