version: "3"

tasks:
    deploy:
        desc: Copy project files to Apache serving directory
        cmds:
            - sudo cp -r . /var/www/html/semana5/tallermvcphp/
            - sudo chown -R apache:apache /var/www/html/semana5/tallermvcphp/
            - sudo chmod -R 755 /var/www/html/semana5/tallermvcphp/
            - sudo semanage fcontext -a -t httpd_sys_content_t "/var/www/html/semana5/tallermvcphp(/.*)?"
            - sudo restorecon -Rv /var/www/html/semana5/tallermvcphp

    clean:
        desc: Remove project files from serving directory
        cmds:
            - sudo rm -rf /var/www/html/semana5/tallermvcphp/*

    unlink:
        desc: Remove symbolic link for development
        cmds:
            - sudo rm /var/www/html/semana5/tallermvcphp
